@extends('user.body.main')
@section('user')

<section id="content-area">
    <div class="container">
        <div class="page-has-sidebar">
            <div class="row">
                <div class="col-sm-12 col-md-9 pull-right">
                    <div id="content-main">                       
                                                <div class="row display-flex faculty-profile-details">
                            <div class="col-xs-12 col-sm-12 col-md-4">
                                <figure class="featured-profile-image">
                                    <img width="265" height="285" alt="" data-src="{{url('public/upload/dean/',$deans->image) }}" class="attachment-full size-full wp-post-image ls-is-cached lazyloaded" src="{{url('public/upload/dean/',$deans->image) }}"><noscript><img width="265" height="285" src="{{url('public/upload/dean/',$deans->image) }}" class="attachment-full size-full wp-post-image" alt="" /></noscript>                                </figure>

                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-8">
                                <h1 class="profile-name">{{ $deans->name }}</h1>
                                <p class="pm-designation">{{ $deans->designation }}</p>
                                                                <p class="pm-email">{{ $deans->email }}</p>
                                                                <p class="pm-links">
                                    <a href="#tab-publications"><i class="fa fa-book"></i></a>
                                    <a href="#tab-publications"><i class="fa fa-file-o"></i></a>
                                    <a href="mailto:advisor@eee.green.edu.bd"><i class="fa fa-envelope"></i></a>
                                </p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="profile-tabs">
                                    <!-- Nav tabs -->
                                                                       
                                    <ul class="nav nav-tabs" role="tablist">

                                        <li role="presentation" class="active"><a href="#tab-education" aria-controls="pan-education" role="tab" data-toggle="tab">Education</a></li>

                                                                                <li role="presentation"><a href="#tab-experience" aria-controls="pan-experience" role="tab" data-toggle="tab">Experience</a></li>
                                                                                                                        <li role="presentation"><a href="#tab-publications" aria-controls="pan-publications" role="tab" data-toggle="tab">Publications</a></li>
                                                                                                                        <li role="presentation"><a href="#tab-awards" aria-controls="pan-awards" role="tab" data-toggle="tab">Awards</a></li>
                                                                                                                        <li role="presentation"><a href="#tab-research" aria-controls="pan-research" role="tab" data-toggle="tab">Research</a></li>
                                                                                                                        <li role="presentation"><a href="#tab-others" aria-controls="pan-others" role="tab" data-toggle="tab">Others</a></li>
                                                                            </ul>
                                    
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane active" id="tab-education">
                                            <div class="tabinner">
                                                <p><strong>Education in Summary</strong></p>
<ul>
<li><strong>1984&nbsp; &nbsp;Doctor of Philosophy (PhD) (Electrical), </strong>University of&nbsp;&nbsp; Ottawa, Canada</li>
<li><strong>1980</strong>&nbsp;<strong>&nbsp; &nbsp;</strong><strong>M.Sc.&nbsp;</strong><strong>Engineering</strong>,&nbsp;Bangladesh University of Engineering and Technology (BUET)</li>
<li><strong>1975</strong>&nbsp; &nbsp; &nbsp;<strong>B.Sc. Engineering (Electrical)</strong>,&nbsp;Bangladesh&nbsp;University&nbsp;of Engineering and Technology (BUET)</li>
<li><strong>1969&nbsp; &nbsp; &nbsp;Higher Secondary Certificate (HSC)&nbsp;</strong>Rajshahi Board,&nbsp;First Division with distinction (Star Marks on average)</li>
<li><strong>1967&nbsp; &nbsp;&nbsp;</strong><strong>Secondary School Certificate (SSC)&nbsp;</strong>Rajshahi Board, First Division with distinction (Letter Marks in Four Subjects.)</li>
</ul>
<p>&nbsp;</p>
                                            </div>

                                                                                    </div>
                                                                                <div role="tabpanel" class="tab-pane" id="tab-experience">
                                            <div class="tabinner">
                                                                                                <p class="MsoNormal" style="text-align: justify"><strong>Professional (1 year)</strong></p>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify">Worked as an <strong>Assistant Engineer</strong><strong> of PWD</strong> of Bangladesh from July 1975 to January&nbsp;1976. The nature of the work was to plan the building electrification and to maintain and operate elevators.</li>
                                                <li class="MsoNormal" style="text-align: justify">Worked as an <strong>Assistant Engineer</strong> in the Power Development Board of Bangladesh from&nbsp;February 1976 to October 1976. The nature of the work was the maintenance and operation&nbsp;of Electric Supply.</li>
                                                </ul>
                                                <p>&nbsp;</p>
                                                <p class="MsoNormal" style="text-align: justify"><b>Teaching and Research (`44 years)</b></p>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify">Currently working as <strong>Distinguished Professor</strong> in the Green University of Bangladesh from July 2017.</li>
                                                <li class="MsoNormal" style="text-align: justify">Worked as a <strong>Visiting Professor</strong> from January 2010 to January 2011 in the Department of&nbsp;Electrical and Electronic Engineering of BRAC University, Dhaka.</li>
                                                <li class="MsoNormal" style="text-align: justify">Worked as a <b>Visiting Professor</b> from January 2001 to January 2002 in the Department of Electrical and Electronic Engineering of Islamic University of Technology, an Institute of OIC.</li>
                                                <li class="MsoNormal" style="text-align: justify">Worked as a V<b>isiting Faculty</b> from September 1991 to June 1994 in the Department of Electrical Engineering of University of Bahrain.</li>
                                                <li class="MsoNormal" style="text-align: justify"><!-- [if !supportLists]-->&nbsp;Worked as a <b>Full Professor</b> from August 1988 to&nbsp; June 2017.</li>
                                                <li class="MsoNormal" style="text-align: justify">Worked&nbsp; as an <b>Associate&nbsp;</b><b>Professor</b> from February 1986 to July 1988.</li>
                                                <li>Worked&nbsp;&nbsp;as an&nbsp;<b style="text-indent: -13.5pt">Assistant Professor</b><span style="text-indent: -13.5pt"><span style="font-family: CG Times, serif"><span style="font-size: 12pt"> from February 1979 to </span>December<span style="font-size: 12pt">, 1980 as well as from&nbsp;</span></span></span><span style="text-indent: -13.5pt">December 1984.</span></li>
                                                <li>Worked&nbsp;&nbsp;as an&nbsp;<b style="text-align: justify;text-indent: -13.5pt">Lecturer </b><span style="text-align: justify;text-indent: -13.5pt">from November 1976 to January, 1979 in the Department of EEE, BUET.</span></li>
                                                <li>Worked as a <b style="text-align: justify;text-indent: -13.5pt">Teaching Assistant</b><span style="text-align: justify;text-indent: -13.5pt"> from January 1981 to November 1984 in the &nbsp;Department of Electrical Engineering of University of Ottawa, Canada. The nature of the work was to demonstrate in the Electrical Machine Laboratory and to teach in the tutorial class.</span></li>
                                                <li>Worked as a<b style="text-align: justify;text-indent: -13.5pt"> System Analyst</b><span style="text-align: justify;text-indent: -13.5pt"> (Part‑time) in the Computer Centre of BUET from April 1986 to December, 1988. The work was to advise the students regarding the problems in their computer programmes and to update the system.</span></li>
                                                </ul>
                                                <p>&nbsp;</p>
                                                <p class="MsoNormal" style="text-align: justify"><strong>Administrative Positions hold</strong><b></b></p>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in"><!-- [if !supportLists]-->&nbsp; &nbsp; &nbsp; &nbsp;Dean, Faculty of EEE, Bangladesh University of Engineering &amp; Technology (BUET).</li>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in"><!-- [if !supportLists]-->&nbsp; &nbsp; &nbsp; &nbsp;Head, Department of EEE, BUET.</li>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in">&nbsp; &nbsp; &nbsp; &nbsp;Provost, Ahsanullah Hall, BUET.</li>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in"><!-- [if !supportLists]-->&nbsp; &nbsp; &nbsp; &nbsp;Assistant Provost, Ahsanullah Hall, BUET.</li>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in"><!-- [if !supportLists]-->&nbsp; &nbsp; &nbsp; &nbsp;Director (Honorary), Power Grid Company of Bangladesh, Government owned Company.</li>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in"><!-- [if !supportLists]-->&nbsp; &nbsp; &nbsp; &nbsp;Director (Honorary), Ashuganj Power Company LTD, Government owned Company, (current).</li>
                                                </ul>
                                                <p>&nbsp;</p>
                                                <p class="MsoNormal" style="text-align: justify"><strong>Academic Responsibilities</strong></p>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in">&nbsp; &nbsp; &nbsp; Technical Chair, 4<sup>th</sup> International Conference on Electrical and Computer Engineering, ICECE 2006, December 19-21, 2006, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in">&nbsp; &nbsp; Project Manager, ‘Short-term training on Reliability and Operational Aspects of a Regional Grid’ – Sponsored by USAID’s South Asia Regional Initiative for Energy (SARI/Energy) Small Grants Program, July 15-17, 2004.</li>
                                                <li class="MsoNormal" style="text-align: justify;text-indent: -0.25in">&nbsp; &nbsp; &nbsp;Course Coordinator, ‘Course 1.7: Strengthening Regional Energy Linkage in South Asia’ – Sponsored by USAID’s South Asia Regional Initiative for Energy&nbsp; (SARI/Energy) Training Program, July 19-23, 2003.</li>
                                                </ul>
                                                <p>&nbsp;</p>
                                                                                            </div>
                                                                                                                                    </div>
                                                                                                                                
                                                                                        <div role="tabpanel" class="tab-pane" id="tab-publications">
                                                                                            <div class="tabinner">
                                                                                                <p class="MsoNormal" style="text-align: justify"><b>LIST OF PUBLICATIONS</b></p>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify">&nbsp;<b>International (Foreign) Refereed Journals</b></li>
                                                </ul>
                                                <ol>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, K.F. Schenk and R.B. Misra, `Expected Energy Production Cost of Two Interconnected Systems with Correlated Demands’, IEEE Transactions, Vol. PAS 102, No.7, pp 2158‑2164, July, 1983.</li>
                                                <li class="MsoNormal" style="text-align: justify">K.F. Schenk, <strong>Q. Ahsan</strong> and S. Vassos, `The Segmentation Method Applied to the Evaluation of Loss of Load Probability of Two Interconnected Systems’, IEEE&nbsp;Transactions, Vol. PAS 103, No.7, pp 1537‑1541, July, 1984.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and K.F. Schenk,`Two Area Production Cost Evaluation by the Segmentation Method’, IEEETransactions, Vol. PAS 104, No.8, pp 2140‑2147, August, 1985.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and K.F. Schenk,&nbsp; `Sensitivity&nbsp; Study of the&nbsp; Cumulant Method for Evaluating Reliability Measures of Two Interconnected Systems’, IEEE Transactions on Reliability, Vol. R‑36, No.4, pp 429‑432, October, 1987.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and S.F. Rahman, `Evaluation of the Reliability and Production Cost of Interconnected Systems with Jointly Owned Units’, IEEE Proceedings Vol. 134, Part‑C, No.6, pp 377‑382, November, 1987.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and M.R. Bhuiyan,&nbsp; `New Approach for Simulating an energy Limited hydro unit`,&nbsp;IEEE Proceedings, Vol. 137, Part‑C, No. 5, September 1990.</li>
                                                <li class="MsoNormal" style="text-align: justify">N.U. Ahmed and <strong>Q. Ahsan</strong>, `A Dynamic Model for Generation Expansion Planning’, Electric Power System Research, 9 (1985) pp 79‑86.</li>
                                                <li class="MsoNormal" style="text-align: justify">K.F. Schenk and <strong>Q. Ahsan</strong>, `Impact of Load Management and Joint Ownership of Generation of Two Interconnected Systems utilizing Joint Cumulants and the Bivariate Gram‑Charlier Expansion’, International Journal of Electrical Power and Energy Systems, Vol.7, No.2,&nbsp;&nbsp; pp 101‑108, April, 1985.</li>
                                                <li class="MsoNormal" style="text-align: justify">K.F. Schenk, <strong>Q. Ahsan</strong> and S. Vassos, `Evaluation of Production Costs of Two Interconnected Electric Power&nbsp; Systems by the Segmentation Method’, Electric power&nbsp;System Research, 8(1984/85) pp 143‑154.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Jamaluddin Ahmed, `Impacts of Load p73&nbsp; Management on Reliability of Two Interconnected Systems’, International Journal of Energy Systems Vol. 8, No.1, pp 49‑53, 1988.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and S.M.Aziz, `The Evaluation of Production Cost of Bangladesh Power Systems: Impacts of East‑West&nbsp; Interconnector’, Journal of the Institution of Engineers, India, Vol. 68, pp 133‑137, February, 1988.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Mahbubur Rahman, `Energy Storage Load Management Scheme: Impacts on the Reliability and Production Cost’, Indian Journal of Power &amp; River Valley Development, (Annual Review), pp 348‑352, October, 1988 (Invited paper).</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, `Load Management: Impacts on the Reliability and Production Costs of Interconnected systems’, International Journal of Electrical Power &amp; Energy Systems, Vol. 12, No. 4, pp. 257‑262, October 1990.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and K.F. Schenk, discussion of “J.P. Stremel, `Reliability Models: Impacts of Model Specification&nbsp; in Generation Expansion Planning’, IEEE Transactions, Vol. PAS 101, No. 10, October, 1982″.</li>
                                                <li class="MsoNormal" style="text-align: justify">K.F. Schenk and <strong>Q. Ahsan</strong>, discussion of “G. Hamoud and&nbsp; E. Neudrof, `Use of the Cumulant Method in computing&nbsp; the frequency and duration Indices of Single and Two Interconnected Systems’, IEEE Transactions, Vol. PAS&nbsp; 102, No.8, August, 1983″.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and S.F. Rahman,&nbsp; discussion of “R. Bhatnagar and S. Rahman, `Direct Load Control: Relationships between Electric Utility Experiences/Assessments and System Characteristics, IEEE Transactions, Vol. PAS 104, No. 8, August, 1985″.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Masum Alam Bakshi, ‘ An Appropriate Method of Evaluating the Reliability of Small Power System:&nbsp; A Case Study.’, Journal of the Institution of Engineers, India, vol.72, pp. 7‑10, April 1991.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, `Sensitivity&nbsp; Study of the&nbsp; Cumulant Method for the Evaluation of Production Costs of Two Interconnected Systems’, International Journal of Electrical Power and Energy System, vol. 13, no. 1 , pp. 21‑27, February , 1991.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, ‘Reliability of Two Interconnected Systems with Jointly owned Units’, International Journal of Electrical Power &amp; Energy Systems , vol. 17, No.6, pp. 363-370,1995.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and A. Hoque, ‘Probabilistic Model of a Wind Turbine Generator for use in Generation Expansion&nbsp; Analysis’Renewable Energy, vol. 4, No. 5, pp. 585-592, 1994.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Masoom Alam Bakshi, `Comparative Study&nbsp; of Different Methods in Power System Reliability&nbsp; Evaluation’, International Journal of Electrical Power and Energy&nbsp;Systems &nbsp;,vol.15, No.1, pp. 4-8, 1995.</li>
                                                <li class="MsoNormal" style="text-align: justify">Aminul Hoque and <strong>Q. Ahsan</strong>,’Wind and Solar Generating Units: Potential Candidate for Generation of an Isolated Area’, Solar Energy, vol. No.5, pp. 395-404, 1995.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, ‘Sensitivity of the Reliability of Two Area Interconnected System to Jointly Owned Units’, International Journal of Electrical Power and Energy Systems. Vol. 20, No.1, pp.1-6, 1998.</li>
                                                <li class="MsoNormal" style="text-align: justify">K.R. Khan, <strong>Q. Ahsan</strong> and M.R. Bhuiyan,’expected Energy Production Cost of Two Area Interconnecting Systems with Joiontly Owned Units’, Electric Power System 69 (2004) page, 115-122.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and M. A. Jalil,’A New technique of Forecasting Hourly load’, International Jounal of Power and Energy Systems, Vol. 25, No.1, page 63-70, 2005.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Md. Quamrul Ahsan</strong>, &nbsp;A. Hasib Chowdhury, S. Shahnawaz Ahmed, I. H. Bhuyan, <span class="MemberType">A. Haque and, H. Rahman</span>, “Technique to Develop Auto Load Shedding and Islanding Scheme to Prevent Power System Blackout”, IEEE Transactions on Power Systm, Vol. 27, pp. 198-205, Feb. 2012.</li>
                                                <li class="MsoNormal" style="text-align: justify">Nahid-Al-Masood, S. M. Fahad, A. B. M. S. Rupu, K. I. Saad and <strong>Q. Ahsan</strong>, “Potential Solution of Power Flow Constraints of Bangladesh Power System”, Journal of Energy and Power Engineering (JEPE), USA, pp. 1315-1319, August, 2012.</li>
                                                <li class="MsoNormal" style="text-align: justify">Nahid-Al-Masood and <strong>Q. Ahsan</strong>, “Dependency of Electrical Demand of Bangladesh Power System on the Weather of the Country”, Journal of Energy and Power Engineering (JEPE), USA, pp. 960-964, June 2012.</li>
                                                <li class="MsoNormal" style="text-align: justify">M. T. Alam and <strong>Q. Ahsan</strong> “A Mathematical Model for the Transient Stability Analysis of a Simultaneous AC-DC Power Transmission System”<i> IEEE</i> <i>Transactions on Power Systems.</i> Vol.33, No 4, pp. 3510-3520, July 2018 .</li>
                                                <li class="MsoNormal" style="text-align: justify">M. T. Alam and <strong>Q. Ahsan</strong> “A Mathematical Model for the Loadability Analysis of a Simultaneous AC-DC Power Transmission System” Electrical Engineering, Springer. Vol. 100, No. 3, pp. 1901-1911, September 2018.</li>
                                                <li class="MsoNormal" style="text-align: justify"><a href="https://onlinelibrary.wiley.com/action/doSearch?ContribAuthorStored=Ahsan%2C+Md+Quamrul"><span style="color: #005274"><strong>Md. Quamrul Ahsan</strong></span></a>&nbsp;, <a href="https://onlinelibrary.wiley.com/action/doSearch?ContribAuthorStored=Chowdhury%2C+Abdul+H"><span style="color: #005274">Abdul H. Chowdhury</span></a>, <a href="https://onlinelibrary.wiley.com/action/doSearch?ContribAuthorStored=Subrina%2C+Samia"><span style="color: #005274">Samia Subrina</span></a>, <a href="https://onlinelibrary.wiley.com/action/doSearch?ContribAuthorStored=Uddin%2C+Md+Forkan"><span style="color: #005274">Md. Forkan Uddin</span></a>, <a href="https://onlinelibrary.wiley.com/action/doSearch?ContribAuthorStored=Roy%2C+Apratim"><span style="color: #005274">Apratim Roy</span></a> and <a href="https://onlinelibrary.wiley.com/action/doSearch?ContribAuthorStored=Islam%2C+Md+Zahurul"><span style="color: #005274">Md. Zahurul Islam</span></a>’ Reliability models of LILO connection and impact on transmission corridor’ International Transactions on Electric Energy Systems, June 2020.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Shuhaib Ahsan, <i>“</i>THE CONCEPT OF MATERIAL TRANSFER FROM ONE PLACE TO OTHER AT THE SPEED OF LIGHT AND REDUCING CAUSES OF EARTHQUAKE: DEVELOPED BASED ON THE HINTS OF QURANIC VERSES”, QURANICA, in Vol. 12 Issue (1), June 2020, Page (19-44). https://ejournal.um.edu.my/index.php/quranica/article/view/24619/11747</li>
                                                <li>Md. Quamrul Ahsan, “<span lang="MS" style="font-size: 11.5pt">A COMPLETE SET OF INHERITANCE SYSTEM IN THE QURAN”,&nbsp;</span>QURANICA Vol. 13, Issue 2, December 2021</li>
                                                </ol>
                                                <ul>
                                                <li class="MsoNormal">&nbsp;<b>National Refereed Journals</b></li>
                                                </ul>
                                                <ol>
                                                <li class="MsoNormal" style="text-align: justify">&nbsp;<strong>Q. Ahsan</strong> and S.F. Rahman, `DC Transmission and DC Link as a Stabilizing tool’, Journal of the IEB, Vol. 7,&nbsp; No.2, April, 1979.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and S.F. Rahman, `The Effect of an AC‑DC Parallel Link on System Stability’, Electrical and Electronic Engineering Research Bulletin, BUET, Dhaka, Vol. 2, No.1, 1980.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, `Joint Ownership of Generation‑Impacts on Reliability and on Production Cost’, Journal of the IEB, Vol. 14, No. 2, April, 1986.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, `Application of the Cumulant Method in the&nbsp; Reliability Evaluation of Interconnected Systems’,&nbsp; Electrical and Electronic Engineering Research Bulletin, BUET, Dhaka, Vol. 3, No.1, 1985. p73</li>
                                                <li class="MsoNormal" style="text-align: justify">S.M. Aziz and <strong>Q. Ahsan</strong>, `The Reliability of Bangladesh Power System: Effects of East‑West Interconnector’, Journal of the IEB, Vol.15, No.3, pp 35‑39, 1987.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Masoom Alam Bakshi, `The Applicability of Cumulant Method to a Small System: A Case Study’,&nbsp; Electrical and Electronic Engineering Research Bulletin, vol. 4, No.1, BUET, pp 7‑14, 1988.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Ehteshamul Huq, ‘ Bibliography on Load &nbsp;porecasting.’ Electrical and Electronics Engineering Research Bulletin, vol. 5, no. 1, BUET, 1989, pp. 34‑38</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, R.Zaman and P.C. Gupta, ‘Artificial Neural – network Applied to Determine the critical clearing time of a power system’ Journal of the IEB, vol.22, No.2,1994</li>
                                                <li class="MsoNormal" style="text-align: justify">S.R.M Ahmed, M.R. Bhuiyan and <strong>Q. Ahsan</strong>, ‘Effect of Reliability Distribution on the Generation System Reliability using Monte Carlo Simulation’, Journal of IEB, Electrical Engineering division, Vol. EE 23, No.I &amp; II, pp. 51-61, Dec. 1995.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. ahsan</strong>, M Alam, R. Karim and H. Rahman, ‘Isolated Home lighting System: The Potential Application of Photovoltaic Cell’, Technical Journal of BUET, 1997, pp.24-33</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, ‘Evaluation of Power Interruption Cost for Residential and Industrial Sectors’, Journal of Energy &amp; Environment, Vol. 3, pp. 119-131, 2004.</li>
                                                <li class="MsoNormal" style="text-align: justify">Mohammad Tawhidul Alam and <strong>Q. Ahsan</strong>, ‘Benefits of Economic Unit Commitment Scheduling Operation in Bangladesh Power System’, vol. EE, 35, No. I, June 2008, pp. 33-39.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, ‘Present Crisis and Future prospect of Bangladesh Power System’, Journal of Electrical Engineering, IEB, vol. EE 38, NO. 1, June 2012, pp. 3-12</li>
                                                <li class="MsoNormal" style="text-align: justify">F. Sadeque and <strong>Q. Ahsan</strong>, ‘Design and Implementation of a Single-Axis Automatic Solar Tracking’, GUB Journal of Science and Engineering, Vol. 1, Issue 1, pp. 1-5, July 2014.</li>
                                                </ol>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify"><b>International Conferences</b></li>
                                                </ul>
                                                <ol>
                                                <li class="MsoNormal" style="text-align: justify">K.F. Schenk and <strong>Q. Ahsan</strong>, `Production Cost of Two Interconnected Systems utilizing the Bivariate Gram‑ Charlier Expansion: Impacts of Load Management and Joint Ownership of Generation’, Proc. Symp. on Computer Analysis of Electric Load Forecasting and Generation Capacity Expansion, NRRI, Columbus, OH, September,1983, pp 256‑267.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and S.M. Aziz, `Two Area Approach in the Probabilistic Simulation of Power&nbsp;&nbsp;&nbsp;&nbsp; System Owned by a Single Utility ‑ A Case Study’, Proceed. Intern. AMSE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Conf. `Modelling &amp; Simulation‘, New Delhi (India), p73&nbsp; October 29‑31, 1987, pp 159‑174.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and M.R. Bhuiyan, ‘ An Application of the Segmentation Method for the Probabilistic Simulation of Multiple Energy Limited Hydro Units.’, Proceedings of&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fourth IEEE Region 10 International Conference, Bombay, India, 1989, pp. 731‑737 (Invited paper).</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Mahbubur Rahman, `The Effects of Load Management on the Reliability and Production Cost’, preprint of International Symposium on Power Systems and Power Plant Control, IFAC, 22‑25 August,1989,Seoul, Korea, pp. 255‑260.</li>
                                                <li class="MsoNormal" style="text-align: justify">A. Hoque, <strong>Q. Ahsan</strong> and W.C. Beattie,’A Statistical Investigation of the Behaviour of an Isolated Wind Turbine’, European Community Wind Energy Conference and Exhibition‘, 8‑12 March,1993, Lubeck, Germany, 1993, pp.355-358.</li>
                                                <li class="MsoNormal" style="text-align: justify">A. Hoque , W.C. Beattie and <strong>Q. Ahsan</strong>, ‘Bangladesh: Energy Problems and rospects’, Proc. 28th UPEC, Staffordshire University, UK, 21-23 September, 1993, pp.235-238.</li>
                                                <li class="MsoNormal" style="text-align: justify">A.Hoque, <strong>Q. Ahsan</strong> and W.C. Beattie, ‘A Comparison of Wind, Photovoltaic and Thermal Generation System for an Isolated Area in Bangladesh’, Proc. 28th UPEC, Staffordshire University, UK, 21-23 September, 1993, pp.239-242.</li>
                                                <li class="MsoNormal" style="text-align: justify">A. Hoque, <strong>Q. Ahsan</strong> and W.C. Beattie, ‘A Load Forecasting Technique for an Isolated Area’, ISEDEM ‘93 (IEEE Singapore Conf.), 27-29 October, 1993, pp 289-293.</li>
                                                <li class="MsoNormal" style="text-align: justify">A. Hoque, W.C. Beattie and <strong>Q. Ahsan</strong>, ‘Alternative Energy Sources in Bangladesh’, Proc. IEE International Conf. on ‘Renewable Energy – Cleanp power 2001’, London, UK, 17-19 November, 1993, Conference Publication 385, pp.19-24</li>
                                                <li class="MsoNormal" style="text-align: justify">A. Hoque, <strong>Q. Ahsan</strong>, A.M.Z. Huq, W.C. Beattie, ‘A Statistical Investigation of the Behaviour of an Isolated Photovoltaic Generator in Bangladesh’, Renewable Energy, Climate Change: Energy and the Environment, Part-III, Reading, UK, 11-16 Sept., 1994, pp.1596-1598.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and S.R. Ahmed, ‘Joint Ownership of Generation: Impacts on the Reliability of Interconnected System’, Proceeding of IEE International Conference on Electricity Sector Development and Demand side Management( ESDDSM95), Kuala Lumpur, Malaysia, 1995, pp.135-141</li>
                                                <li class="MsoNormal" style="text-align: justify">B. Chakma, U.K. Saha, J.K. Khisa and <strong>Q. Ahsan</strong>,’Economic Benefits: Use of PV cells for an office lighting,’ Proceedings of International Symposium on Advances in Alternative &amp; Renewable Energy, pp.542-549, 22-24 July, 1997, Johor Bahru, Malaysia.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, M. Alam, R. Karim and H. Rahman, `Isolated Home lightning system:The Potential application of Photovoltaic Cell’, Proceedings of International Conference on Energy Research and Development, Kuwait, 9-11 November, 1998.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and M. Alam,’Solar Power Lantern for flood affectd areas’, IEEE winter Meeting, January 23-27, 2000, Singapore.</li>
                                                <li class="MsoNormal" style="text-align: justify">M. A. Jalil and <strong>Q. Ahsan</strong>,’ Impacts of load Model on the Generation Expantion Plan of a Utility’, Proceeding of Second International Conference on Energy research &amp; Development (ICERD-2), April 8-10, 2002, pp 139-150, state of Kuwait.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Moin Uddin,’ A Probabilistic Approach of Electrical Energy Forecasting’, IEE Instrumentation and Measurement Technology Conference, Ottawa, Canada, 17-19 May, 2005 (submitted).</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, M. Alam, R. Karim and H. Rahman, ‘Reliability Worth of Power Interruption in Small Industries’, Canadian Reliability and Maintainability Symposium, Ottawa, Canada, October 16-17, 2003.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Lt. Col Moin Uddin, ‘A Probabilistic Approach of Electrical Energy Forecasting’, Proceedings of 2005 IEEE Instrumentation and Measurement Technology Conference, Ottawa, Canada, 17-19 May 2005.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Mohammad Tawhidul Alam, ’Electrical Power crisis in Bangladesh: Impacts of Optimal Use of Energy Limited Hydro Units on the System Reliability and production Cost’, Proceedings of 2007, IEEE Electrical Power Conference , Montreal, Canada, 25-26 October, 2007.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, A. Hasib Chowdhury, S. Shahnawaz Ahmed, I. H. Bhuyan, <span class="MemberType">A. Haque, H. Rahman</span>, “Frequency dependent auto load shedding scheme to prevent blackout in Bangladesh Power System”, Proceedings of the 4th IASTED Asian Conference on <span class="confname">Power and Energy Systems</span>, 24-26 November 2010, Phuket, Thailand.</li>
                                                <li class="MsoNormal" style="text-align: justify">Taif Hossain Rocky ,Sumit Mazumder Ami and <strong>Q Ahsan</strong>, ‘<b>&nbsp; </b><span style="font-size: 12pt;font-family: TimesNewRoman, serif">A Technique of Collecting Online Data for Forecasting the Output Capacity of a Remotely Located WTG’, IEEE Regional Conference, Tencon-2010, Fukuoka, Japan, November, 2010.</span></li>
                                                <li class="MsoNormal" style="text-align: justify">Nahid-Al-Masood and <strong>Q. Ahsan</strong>, “Electrical Demand of Bangladesh Power System: Dependence on the Weather of the Country”, 3rd Asia-Pacific Power and Energy Engineering Conference (APPEEC), China, Vol. 2, pp. 17-20, 2011.</li>
                                                <li class="MsoNormal" style="text-align: justify">Nahid-Al-Masood, S. M. Fahad, A. B. M. S. Rupu, K. I. Saad and <strong>Q. Ahsan</strong>, “Volt Ampere Reactive Compensation: Potential Solution of Power Flow Constraints of Bangladesh Power System”, 3rd Asia-Pacific Power and Energy Engineering Conference (APPEEC), China, Vol. 3, pp. 13-16, 2011.</li>
                                                </ol>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify"><strong>National Conference</strong></li>
                                                </ul>
                                                <ol>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Z. Huq, `Assessment of Relaibility of Bangladesh Electric Power Generation&nbsp;&nbsp; System&nbsp; ‑&nbsp; Part I’,&nbsp;&nbsp; presented&nbsp;&nbsp; at&nbsp;&nbsp; the&nbsp;&nbsp; International&nbsp; Conference&nbsp; on&nbsp;&nbsp;&nbsp; Energy&nbsp;Planning for Bangladesh, Nov. 21‑24, 1985, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and S.F. Rahman, `Load Management: Impacts on System Reliability’, presented at 30th Annual Convention of IEB.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Mahbubur Rahman, `The Effects of Load Management on the Reliability and Production Cost of&nbsp; a Power System ‑ A Case Study’, presented at the&nbsp; 14th Annual Convention of BAS, 1989, Dhaka.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Mahbubur Rahman, `A Probabilistic Approach in evaluating the possible efficient use&nbsp; of hydro power at Kaptai, presented in the 33rd Annual&nbsp; Convention of IEB,&nbsp; Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Aminul Haque, ‘ A New Technique of Load&nbsp; Forcasting for an Isolated Area.’, presented&nbsp; at the&nbsp; 34th Annual Convention of the IEB, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, K. Ahmed, M.S. Ahmed and G.T. Rasul, ‘ Future Electric Demad in Bangladesh.’,&nbsp; 15th annual Convention of BAS, 1990.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>,&nbsp; ‘Rural Home lighting: Use of a Solar Powered Lantern,’ Proceedings of National Seminar on Renewable Energy for Poverty Alleviation,&nbsp; pp. 30-38, Dhaka, Bangladesh. 21-23 October, 1997.</li>
                                                <li class="MsoNormal" style="text-align: justify">M. A. Jalil and <strong>Q. Ahsan</strong>, ’Banladesh Power System Master Plan: Impacts of Load Model’, Proceedins of ICECE 2001, Dhaka, 2001, pp. 127-130.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, A. Bhuiyan, N.H. Khan and H. Kabir, ‘Quantification of Customer’s loss Due to Power Failure in Residential Sector’, Proceedins of ICECE 2002, Dhaka, 2002, pp. 225-228.</li>
                                                <li class="MsoNormal" style="text-align: justify">Moin Uddin and <strong>Q. Ahsan</strong>, ‘Expected Status of Natural Gas in Bangladesh in Meeting the Electrical Demand in the Next Twenty Five Years’, Proceedings of ICECE 2004, Dhaka, 2004, pp. 470-473.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong>, M.F. Hossain, R. H. Bhuiyan and M. N.Islam,’Electrical Faults Causing Fire in Buildings’, Souvenir of ICECE –2004, Dhaka, 2004, pp. 43-51.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and Akhil Chandra Das,’Cost of Electric Service Interruption: Awarness among Consumers and Utilities’, Proceedings of ICECE 2006, Dhaka, 2006, pp. 128-131.</li>
                                                <li class="MsoNormal" style="text-align: justify">Mohammad Tawhidul Alam and <strong>Q. Ahsan</strong>, Savings of Naturul Gas Through Optional Operation of Bangladesh Power System, ICECE 2008, pp. 688-692, 20-22, December 2008 Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">Abdul Hasib Chowdhury and <strong>Q. Ahsan</strong>, Evaluation of Optional Capacity and Location of East West Interconnector using Tie Line Planning Approach, ICECE 2008, pp. 366-369, December 2008 Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">Moin Uddin and <strong>Q. Ahsan</strong>, ‘Future Electric Energy Demand of Bangladesh’ ICECE 2008, pp. 370-373. December 2008 Dhaka, Bangladesh</li>
                                                <li class="MsoNormal" style="text-align: justify">R. Sarwar, R. Chakrabartty, N. Ahmed, K. M. Ahmed, <strong>Q. Ahsan</strong>, ‘<span style="font-size: 12pt;font-family: TimesNewRoman, serif">Effect of Daylight Saving Time on Bangladesh Power System’, </span>6th International Conference on Electrical and Computer Engineering, pp.291-293, ICECE 2010, 18-20 December 2010, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">K. N. Hasan,&nbsp; <strong>Q.&nbsp; Ahsan</strong>, M. Hussain, K.&nbsp; Saifullah, ‘Reliability &nbsp;Analysis of Mobile Communication System of Bangladesh’, 6th International Conference on Electrical and Computer Engineering, ICECE 2010, 18-20 December 2010, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">S. Habib and <strong>Q. Ahsan</strong>, ‘Effect of Insulating Oil Degradation on Power Transformer Capacitance’, 7th International Conference on Electrical and Computer Engineering, ICECE 2012, 20-22 December 2012, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">M. Safiullah, H. Rahman and <strong>Q. Ahsan</strong>, ‘Study of Impacts on Operation of Island and Frequency Based Auto Load Shedding to Improve&nbsp; Service Reliability using CYME PSAF’, 7th International Conference on Electrical and Computer Engineering, ICECE 2012, 20-22 December 2012, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">A. Haque, M. A. Rahman and <strong>Q. Ahsan</strong>, ‘Building Integrated Photovoltaic System: Cost Effectiveness’, 7th International Conference on Electrical and Computer Engineering, ICECE 2012, 20-22 December 2012, Dhaka, Bangladesh</li>
                                                <li class="MsoNormal" style="text-align: justify">Mohammad Tawhidul Alam and <strong>Q. Ahsan</strong>, ‘ Analytical Approach to Investigate the Loadability of a Long Transmission Line for Simultaneous AC-DC Power Flow’, 8th International Conference on Electrical and Computer Engineering 20-22 December, 2014, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">Mohammad Tawhidul Alam and <strong>Q. Ahsan</strong>, ‘Analytical Approach to Investigate the Stability of a System with Simultaneous AC-DC Power Flow through Existing AC Transmission Line ’, 8th International Conference on Electrical and Computer Engineering 20-22 December, 2014, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">Ashraful Haque, Sheikh JawadIlham and <strong>Q. Ahsan</strong>, ‘Matching of Artificial Limb with Residual Human Limb by Capacitance Measurement Technique’, 8th International Conference on Electrical and Computer Engineering 20-22 December, 2014, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">Md Ayubur Rahman Khan and <strong>Md Quamrul Ahsan</strong>, ‘Development and Performance Analysis of a Two-Phase Induction Motor in the Frame and Core of a Single-Phase Induction Motor’, 8th International Conference on Electrical and Computer Engineering 20-22 December, 2014, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">Jamil Wahid and <strong>Q. Ahsan</strong>, ‘Detection of Impurities in Water by Measuring Capacitance’, 8th International Conference on Electrical and Computer Engineering 20-22 December, 2014, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">Jubair Yusuf, Fuad Sakib and <strong>Q. Ahsan</strong>, ‘Study of Blackout prevention of a Power System’ 9th International Conference on Electrical and Computer Engineering 20-22 December, 2016, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">Mohammad Tawhidul Alam, Rabayet Sadnan, Irtiza Haque, Mosfeiqur Rahman and Quamrul Ahsan, ‘Loadability Improvement of an Existing AC Line by Transmitting Simultaneous Ac and DC Power’ 9th International Conference on Electrical and Computer Engineering 20-22 December, 2016, Dhaka, Bangladesh.</li>
                                                </ol>
                                                <ul>
                                                <li class="MsoNormal">&nbsp;<b>Books</b></li>
                                                </ul>
                                                <ol>
                                                <li class="MsoNormal" style="text-align: justify">&nbsp;<strong>Q. Ahsan</strong>, A. Quium, F. Elahi and A. Rouf, ‘ Programming In FORTRAN 77’, published by Payra Prakashani, 6, Hay‑ batnagarlane, Babubazar, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Q. Ahsan</strong> and M. Alam, ‘Solar Powered Lantern for Flood Affected Areas’ – Chapter of Engineering Concerns of Flood, ISBN 984-823-0025, Mother Printers, Nilkhet, Dhaka, Bangladesh.</li>
                                                <li class="MsoNormal" style="text-align: justify">S. Rahman, S. S Ahmed, S.I. Khan, <strong>Q. Ahsan</strong>, S.Alam and K.M Rahman, ‘Sloar Home System’, ISBN: 978-984-33-7228-4, Department of Electrical and Electronic Engineering, Bangladesh University of Engineering and Technology, Dhaka.</li>
                                                <li class="MsoNormal" style="text-align: justify"><strong>Md. Quamrul Ahsan</strong>, ‘Korane Bornito Farayez Babosta (Lwas of Inheritance revealed in the Quran) Media Plus, Elephant Road, Dhaka, January 2020.</li>
                                                </ol>
                                            </div>
                                                                                    </div>
                                                                                                                        <div role="tabpanel" class="tab-pane" id="tab-awards">
                                            <div class="tabinner">
                                                <p class="MsoNormal" style="text-align: justify"><b>HONOURS AND AWARDS</b></p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">1.&nbsp;&nbsp; <strong>Best Research Paper Award</strong> of Power Division, Ministry of Energy &amp; Mineral Resources,</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Govt. Of Bangladesh, 2010</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">2&nbsp;&nbsp;&nbsp; <strong>Best Research Award</strong> of Bangladesh University Grants Commission, 1990.</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">3.&nbsp;&nbsp; <strong>Best Teacher Award</strong> of Bangladesh University of Engineering &amp; Technology, 1987.</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">4.&nbsp;&nbsp; <strong>Research Fellow</strong> of University of Ottawa, Canada, 1981‑1984.</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt"><span style="font-family: CG Times, serif"><span style="font-size: 12pt">5.</span></span>&nbsp;&nbsp; <span style="font-family: CG Times, serif"><strong><span style="font-size: 12pt">Technical </span>Scholarship</strong><span style="font-size: 12pt">&nbsp;of </span></span>Bangladesh University<span style="font-family: CG Times, serif"><span style="font-size: 12pt"> of Engineering &amp; Technology,</span></span></p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1970‑1975.</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">6.&nbsp; <strong>Talent Pool Scholarship</strong> of Board of Intermediate &amp; Secondary Education, Bangladesh,</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">&nbsp;&nbsp;&nbsp;&nbsp; 1967‑69.</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">7.&nbsp; <strong>Secondary School Merit Scholarship</strong> of Directorate of Public Instructions, Bangladesh,</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">&nbsp;&nbsp;&nbsp;&nbsp; 1965‑1966.</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">8.&nbsp; <strong>Primary School Merit Scholarship</strong> of Directorate of Public Instructions, Bangladesh,</p>
                                                <p class="MsoNormal" style="margin-left: 22.5pt;text-align: justify;text-indent: -22.5pt">&nbsp;&nbsp;&nbsp;&nbsp; 1962‑64 (<strong>Stood 1st</strong> ).</p>
                                            </div>
                                                                                    </div>
                                                                                                                        <div role="tabpanel" class="tab-pane" id="tab-research">
                                            <div class="tabinner">
                                                <p class="MsoNormal" style="text-align: justify"><b>FIELD OF INTEREST</b></p>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;Power System Reliability.</li>
                                                <li class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp; Power System Planning.</li>
                                                <li class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp; &nbsp;Load Management.</li>
                                                <li>&nbsp;&nbsp;&nbsp;&nbsp; Renewable Energy.</li>
                                                </ul>
                                                <p>&nbsp;</p>
                                                <p class="MsoNormal" style="text-align: justify"><b>SUPERVISED M.Sc. / PhD THESIS</b><b></b></p>
                                                <p class="MsoNormal" style="text-align: justify"><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <u>Name of the thesis</u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>Degree</u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </b></p>
                                                <p class="MsoNormal" style="text-align: justify"><b>&nbsp;</b></p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 1. A Methodology for analyzing Electrical Energy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;Ph.D.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp; Options for Isolated Areas.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 2. Evaluation of Two Area Interconnected Systems&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; M.Sc.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; as a Single Area System.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 3. Sensitivity Study of Different Methods of&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; M.Sc.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Power System Reliability Evaluation.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 4. Effects of Location of Jointly Owned Unit on&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; M.Sc.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; System Reliability and Production Cost.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 5. Impact of Load Management on Reliability and&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; M.Sc.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Production Cost.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 6. Probabilistic Simulation of Energy Limited&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M.Sc.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Multi‑ Hydro Units.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 7. Evaluation of Production Cost of Multi ‑ Area&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; M.Sc.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Interconnected Power System using Segmentation</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Method.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 8. CAI for Teaching Course on Mathematics.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PGD</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp; 9. An approach to evaluate the expected energy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;M.Engg.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Generation of two area interconnected system</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; With jointly owned units located in one of the</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Areas.</p>
                                                <p class="MsoNormal" style="text-align: justify">10. Comparison of the reliability and production&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; M.Sc</p>
                                                <p class="MsoNormal" style="margin-left: .25in;text-align: justify">&nbsp;Cost of the generation system of Bangladesh</p>
                                                <p class="MsoNormal" style="margin-left: .25in;text-align: justify">&nbsp;Power system master Plan</p>
                                                <p class="MsoNormal" style="text-align: justify">11. Development of a methodology for long term&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;M.Sc</p>
                                                <p class="MsoNormal" style="margin-left: .25in;text-align: justify">Hourly electrical load forecasting and assessment</p>
                                                <p class="MsoNormal" style="margin-left: .25in;text-align: justify">Of gas requirement</p>
                                                <p class="MsoNormal" style="text-align: justify">12. Electric power interruption cost and its correlation&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; M.Sc</p>
                                                <p class="MsoNormal" style="margin-left: .25in;text-align: justify">With the system reliability</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;13 A new methodology for planning tie lines between&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ph.D.</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; interconnected power systems</p>
                                                <p class="MsoNormal" style="text-align: justify">14 Evaluation of fuel cost savings for optimaloading&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; M.Sc</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp; of the generating units of Bangladesh power system</p>
                                                <p class="MsoNormal" style="text-align: justify">15 Evaluation of the impacts of different factors on the&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M.Sc</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp; reliability of a local public switched telephone</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp; network exchange</p>
                                                <p class="MsoNormal" style="text-align: justify">16 Development of Database and identification of causes</p>
                                                <p class="MsoNormal" style="text-align: justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; of fire in buildings of Bangladesh from electrical faults&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; M.Engg.</p>
                                                <p>&nbsp;</p>
                                                <p class="References" style="line-height: 115%">17 <span style="font-size: 12.0pt;line-height: 115%">&nbsp;Development of an Analytical Model of a Simultaneous&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ph.D.</span></p>
                                                <p class="References" style="line-height: 115%"><span style="font-size: 12.0pt;line-height: 115%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; AC-DC Power Transmission System</span><b></b></p>
                                                <p class="MsoNormal" style="margin-left: .25in;text-align: justify"><b>&nbsp;</b></p>
                                                <p>&nbsp;</p>
                                                <p>&nbsp;</p>
                                                <p>&nbsp;</p>
                                                <p class="MsoNormal" style="text-align: justify"><b>REVIEWER</b><b></b></p>
                                                <p class="MsoNormal" style="text-align: justify"><b>&nbsp;</b></p>
                                                <ul>
                                                <li class="MsoNormal" style="text-align: justify">International Journal of Energy System Published by IASTED (International Association&nbsp;Of Science and Technology for Energy Development).</li>
                                                <li class="MsoNormal" style="text-align: justify">&nbsp;IEEE Transactions on Reliability.</li>
                                                <li class="MsoNormal" style="text-align: justify">International Journal of Electrical Power &amp; Energy Systems; Published from Westbury House, Bury Street, Guildford Surrey GUZ 5BH England.</li>
                                                <li class="MsoNormal" style="text-align: justify">IEE Proc. Generation, Transmission &amp; Distribution</li>
                                                <li class="MsoNormal" style="text-align: justify">Journal of IEB (Institute of Engineers, Bangladesh).</li>
                                                <li class="MsoNormal" style="text-align: justify">Journal of Energy and Environment, BUET, Dhaka, Bangladesh</li>
                                                </ul>
                                                <p>&nbsp;</p>
                                                <p>&nbsp;</p>
                                                                                            </div>
                                                                                    </div>
                                                                                                                        <div role="tabpanel" class="tab-pane" id="tab-others">
                                            <div class="tabinner">
                                                <p class="MsoNormal" style="text-align:                 justify"><b>MEMBERSHIP</b></p>
                                                        <ul>
                                                        <li class="MsoNormal" style="text-align: justify">Member of IEEE (Member No: 4871828 )</li>
                                                        <li class="MsoNormal" style="text-align: justify">Former Member of CASR (Committee for Advanced Studies and&nbsp;&nbsp; Research) at the&nbsp;University of Engineering &amp; Technology&nbsp; Dhaka, Bangladesh.</li>
                                                        <li class="MsoNormal" style="text-align: justify">Member of Academic Committee at ICTVTR (Islamic Center for Technical and Vocational Training &amp; Research) from 1989 to 1991.</li>
                                                        <li class="MsoNormal" style="text-align: justify">Former Member of the Finance Committee of BUET.</li>
                                                        </ul>
                                                        <p>&nbsp;</p>
                                                        <p class="MsoNormal" style="text-align: justify"><b>Members of Different Committees and projects</b></p>
                                                        <ul>
                                                        <li class="MsoNormal" style="text-align: justify"><b>&nbsp;</b><!-- [if !supportLists]--><b>Committees</b></li>
                                                        </ul>
                                                        <p class="MsoNormal" style="margin-left: .75in;text-align: justify"><b>&nbsp;</b></p>
                                                        <p class="MsoNormal" style="margin-bottom: 6.0pt;text-align: justify">1.&nbsp; Served as a member in the Expert Committee formed by Power Grid Company of Bangladesh&nbsp; Ltd. (PGCB) to facilitate effective transfer of technology for the&nbsp; National Load Despatch Centre&nbsp; Project financed by World Bank and Asian Development Bank,&nbsp; September 1999 – March 2000.</p>
                                                        <p class="MsoNormal" style="margin-bottom: 6.0pt;text-align: justify">2. Visited Purdue University, Indiana, USA, Mumbai, India and Colombo, Srilanka for exchange of ideas regarding regional energy cooperation&nbsp;&nbsp;&nbsp; under a link program sponsored by SARI/E program of USAID, October 2003.</p>
                                                        <p class="MsoBodyTextIndent3" style="margin-left: 0in">3.&nbsp; Member of the national committee (November – December 2007) formed by the Power Division of Ministry of Power, Energy and Mineral Resources of GOB for finding facts and making recommendations in relation to the blackouts in the Bangladesh grid system twice on 16 November 2007 following a devastating cyclone named SIDR.</p>
                                                        <p class="MsoBodyTextIndent3" style="margin-left: 0in">4.&nbsp; Member of the national committee (December 2007- February 2008) formed by the Power Division of Ministry of Power, Energy and Mineral Resources of GOB for investigations into the cause of grid failure on 15 December 2007.</p>
                                                        <p class="MsoBodyTextIndent3" style="margin-left: 0in">5. Member of the national committee to find the causes of failure of 6<sup>th</sup> unit of Ghorashal Power Station, 2010 (July)</p>
                                                        <p class="MsoNormal" style="text-align: justify"><b>&nbsp;</b></p>
                                                        <ul>
                                                        <li class="MsoNoSpacing" style="text-indent: -0.75in"><!-- [if !supportLists]--><b>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</b><b>Projects</b></li>
                                                        </ul>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->1.&nbsp;&nbsp;&nbsp;Team Leader, BUET experts team for the ‘Feasibility study of own generation of Civil Aviation Authority of Bangladesh (reliability, economic and environmental aspects)’, 2014.</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->2.&nbsp;&nbsp;Team Leader, BUET experts team for ‘Preparation of Specification, Bid Document and Verification of mathematical models and software functionalities for Power Plant Simulator (PPS)’, 2013-2014.</p>
                                                        <p class="MsoBodyTextIndent3" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->3.&nbsp;&nbsp;&nbsp;&nbsp;Team Leader, BUET expert team to carry out “Comparative analysis among different options for connecting AKSPL sub-station with the national grid,” for the Power Grid Company of Bangladesh, Power Division of Ministry of Power, Energy and Mineral Resources of GOB; 2013.</p>
                                                        <p class="MsoBodyTextIndent3" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->4.&nbsp;&nbsp;&nbsp;&nbsp;Team Leader, BUET expert team to carry out “Impact studies of steel mills on Bangladesh Power System,” for steel mill projects of BSRM, Abul Khair Steel Mills, Modern Steel and Re-rolling Mills etc. for the Power Grid Company of Bangladesh, Power Division of Ministry of Power, Energy and Mineral Resources of GOB; 2010 to 2014.</p>
                                                        <p class="MsoBodyTextIndent3" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->5.&nbsp;&nbsp;Team leader, expert team for USAID funded “Preliminary review of PGCB Grid System and Code completed with recommended updats”, 2012.</p>
                                                        <p class="MsoBodyTextIndent3" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <!--[endif]-->Member, expert team for USAID funded “Preliminary investigation of current transmission tariff”, 2012.</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->7.&nbsp;&nbsp;&nbsp;Member, BUET expert team for the ‘Feasibility of cogeneration in sugar mills of Bangladesh Sugar and Food Industries Corporation’, 2010.</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->8.&nbsp;&nbsp;&nbsp;Member, BUET expert team for determination of under frequency relay settings for the feeders for auto load shedding and the frequency ranges for the generators in&nbsp; Bangladesh Power System to avert blackout&nbsp; as requested by Power Grid Company of Bangladesh (PGCB) Ltd; ( January – December 2009).</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->9.&nbsp;&nbsp;&nbsp;Member, BUET expert team for conducting electromagnetic transients and stability studies to identify the root cause of blackout&nbsp;in the Bangladesh grid system&nbsp;occurring on 15 December 2007.</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->10.&nbsp; <!--[endif]-->Member, BUET expert team for conducting transient stability studies to identify the exact causes of blackout&nbsp;in the Bangladesh grid system&nbsp;occurring on 16 November 2007 following a devastating cyclone named SIDR.</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->11.&nbsp; <!--[endif]-->Served as a resource person and coordinator under South Asia Regional Initiative in Energy<span style="letter-spacing: -.1pt"> (SARI/E) Program of USAID&nbsp; in (i) evaluating research reports on <i>cross-border power trading in South Asia </i>prepared by “Nexant”, April-May 2003, (ii) the Course 1.7: “<i>Strengthening Regional Energy Linkages in South Asia</i>” sponsored and organized by AED (Academy for Educational Development) in collaboration with BUET in Dhaka (19-23 July 2003),</span> and (iii)the short term training “<i>Reliability and Operational Aspects of a Regional Grid</i>” sponsored by Winrock International and organized by BUET in Dhaka (15-17 July 2004)<span style="letter-spacing: -.1pt">.</span></p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->12.&nbsp; <!--[endif]-->Team Leader, BUET expert team for review , correction and updating of&nbsp; the technical specifications in the Bid Documents prepared by M/S. Worley International Ltd., New Zealand for design, manufacture, supply, installation, testing&nbsp; and commissioning of&nbsp; a&nbsp; SCADA , an EMS and a Communication backbone system covering 101 sites by&nbsp; about 2250 km optical fibre cable&nbsp; under a new National Load Despatch Centre Project&nbsp; for the&nbsp; grid&nbsp; system to be owned by Power Grid Company of Bangladesh&nbsp; Ltd. (PGCB); 1999&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->13.&nbsp; <!--[endif]-->Member, BUET experts’ team on the consultancy project : “Study on Effects of Flicker Voltage&nbsp; and Harmonics on Bangladesh Grid System at the Point of Common Coupling (PCC) Due to the Planned 18 MVA Electric Arc Furnace at Chittagong Steel Mills”, completed at BUET in 1990.</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->14.&nbsp;Member, BUET expert team appointed as consultant (March -November 2008) by the Bangladesh Water Development Board (BWDB) for supervision and acceptance of the commissioning test in&nbsp;the Ganges Kabodakh Irrigation Project’s rehabilitation &nbsp;that involved replacement of&nbsp;three large pumps and synchronous motors each 3 MW by the new ones under Japanese grant.</p>
                                                        <p class="MsoNoSpacing" style="text-align: justify;text-indent: -.25in;margin: 6.0pt 0in .0001pt .25in"><!-- [if !supportLists]-->15.&nbsp; <!--[endif]-->Team leader of Technical Audit of Solar Home System (SHS) of the Infrastructure Development Company of Bangladesh, IDCOL, Bangladesh.</p>
                                                        <p>&nbsp;</p>
                                                        <p class="MsoNormal" style="text-align: justify"><b>&nbsp;</b></p>
                                                        <p>&nbsp;</p>
                                            </div>
                                                                                    </div>
                                                                            </div>
                                                                    </div>
                            </div>
                        </div>
                                            </div>
                </div>
            
        
            </div>
        </form>
        			</div></aside>                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@endsection
