@extends('user.body.main')
@section('user')


<div _ngcontent-c4=""><div _ngcontent-c4="" class="row text-center" style="background: #e1dce8"><div _ngcontent-c4="" class="col-sm  accent-fg  h-30 fs-20 amarnath pl-20 pr-20"><h3> Available Programs</h3> </div><div _ngcontent-c4=""><div _ngcontent-c4="" class="container" style="min-height: -webkit-fill-available;"><div _ngcontent-c4="" class="row "><div _ngcontent-c4="" class="col-2"></div><!----><div _ngcontent-c4="" class="col-sm fs-14 pt-20 text-justify"><h2 style="text-align: center;" align="justify"><span style="background-color: #ffffff; color: #800080;"><a style="background-color: #ffffff; color: #800080;" href="../../../academic/department/bengali"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large; background-color: #ffffff;">B.A Honours in Bengali</span></span></strong></a></span></h2><br>
    <h2 style="text-align: center;" align="justify"><span style="color: #800080; background-color: #ffffff;"><a style="color: #800080; background-color: #ffffff;" href="../../../academic/department/english"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large; background-color: #ffffff;">B.A Honours in English</span></span></strong></a></span></h2>
    <h2 style="text-align: center;" align="justify"><span style="color: #800080; background-color: #ffffff;"><a style="color: #800080; background-color: #ffffff;" href="../../../academic/department/business-administration"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large; background-color: #ffffff;">BBA</span></span></strong></a></span></h2>
    <h2 style="text-align: center;" align="justify"><span style="color: #800080; background-color: #ffffff;"><a style="color: #800080; background-color: #ffffff;" href="../../../academic/department/agriculture"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large; background-color: #ffffff;">BSc Honours in Agriculture</span></span></strong></a></span></h2>
    <h2 style="text-align: center;" align="justify"><span style="color: #800080; background-color: #ffffff;"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large; background-color: #ffffff;"><a style="color: #800080; background-color: #ffffff;" href="../../../academic/department/ice">BSc Engineering in Information and Communication Technology</a> </span></span></strong></span></h2>
    <h2 style="text-align: center;" align="justify"><span style="color: #800080;"><strong> <span style="font-family: Times New Roman, serif;"><span style="font-size: large;"><a style="color: #800080;" href="../../../academic/department/cse">BSc Engineering in Computer Science</a> </span></span></strong></span></h2>
    <h2 style="text-align: center;" align="justify"><span style="color: #800080;"><a style="color: #800080;" href="../../../academic/department/eee"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large;">BSc in Electrical and Electronic Engineering </span></span></strong></a></span></h2>
    <p style="text-align: center;"><span style="color: #800080;"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large;"><a style="color: #800080;" href="../../../academic/department/business-administration">MBA</a></span></span></strong></span></p>
    <p style="text-align: center;"><span style="color: #800080;"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large;"><a style="color: #800080;" href="../../../academic/department/bengali">M.A in Bengali</a></span></span></strong></span></p>
    <p style="text-align: center;"><a href="../../../academic/department/MPEd"><span style="color: #800080;"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large;">MPEd</span></span></strong></span></a></p>
    <h2 style="text-align: center;" align="justify"><span style="color: #800080; background-color: #ffffff;"><a style="color: #800080; background-color: #ffffff;" href="../../../academic/department/agriculture"><strong><span style="font-family: Times New Roman, serif;"><span style="font-size: large; background-color: #ffffff;">BSc Honours in Microbiology</span></span></strong></a></span></h2>


    <p>&nbsp;</p></div><!----><div _ngcontent-c4="" class="col-2"></div></div></div></div></app-static-desined-view>


    @endsection